### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by LuizF14** [LuizF14/impossible-tik-tak-toe#1]
### Tik-tak-toe impossible bot
- [ ] Create game tree generator
- [ ] Store game tree
- [ ] Filter game tree
### Create game GUI
